#logging
logging:
  level:
    "logging.level.org.springframework":
                              "DEBUG"
  file: D:/spring-boot-log/spring_boot.log

#spring
spring:
  datasource:  # DataSource
    url: jdbc:mysql:///ms_sale
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  mvc:  #springmvc
    view:
      prefix: /jsp/
      suffix: .jsp
  jpa:   #jpa
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database: MYSQL
    show-sql: true
  thymeleaf:  #thymeleaf
    mode: HTML5
    prefix: /templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: false
  redis: #redis
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
  mail:
    host: smtp.qq.com
    username: 2488837660@qq.com
    password: maisoagjksywebjh
    properties:
      mail.smtp.auth: true
      mail.smtp.strttls.enable: true
      mail.smtp.strttls.required: true
  http:
    multipart:  # 文件上传
      enabled: true
      max-file-size: 2MB
      max-request-size: 20MB
      file-size-threshold: 512KB     
      location: /image
      

    
 
      
  