server:
  port: 7900

spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: https://gitee.com/snowstorms/ConfigHub.git
          search-paths: ms_lease_config
          username: snowstorms
          password: XieYuCheng123
      label: master
  application:
    name: ConfigServer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/