server:
  port: 7900

spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: https://github.com/snowstormsss/ConfigHub
          search-paths: ms_lease_config
      label: master
  application:
    name: ConfigServer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/