server:
  port: 8888

spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: https://github.com/snowstormsss/ConfigHub
          search-paths: ms_lease_config
      label: master