server:
  port: 7960

spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    cache: false
    content-type: text/html
  http:
    multipart:  # 文件上传
      enabled: true
      max-file-size: 2MB
      max-request-size: 20MB
      file-size-threshold: 512KB
      location: /image
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver