server:
  port: 7961

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis: #redis
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
  mail:
    host: smtp.qq.com
    username: 2488837660@qq.com
    password: maisoagjksywebjh
    properties:
      mail.smtp.auth: true
      mail.smtp.strttls.enable: true
      mail.smtp.strttls.required: true
  http:
    multipart:  # 文件上传
      enabled: true
      max-file-size: 2MB
      max-request-size: 20MB
      file-size-threshold: 512KB
      location: /image