server:
  port: 7961

spring:
  http:
    multipart:  # 文件上传
      enabled: true
      max-file-size: 2MB
      max-request-size: 20MB
      file-size-threshold: 512KB
      location: /image
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  application:
    name: application-serverconfig
  cloud:
    config:
      label: master
      profile: dev
      uri: http://127.0.0.1:8888/

mybatis:
  mapper-locations: classpath:mapper/*.xml



