server:
  port: 7962

spring:
  http:
    multipart:  # 文件上传
      enabled: true
      max-file-size: 2MB
      max-request-size: 20MB
      file-size-threshold: 512KB
      location: /image
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  application:
    name: CoreServer

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/



